Repository UniqueNetwork/unique-chain, pull requests merged in 2022-12, with the labels that each got.

#774 Use patch-branches for node-only-update tests
  .env
Labels: node-only-update, CI-node-only-update

#801 Fix xcm
  pallets/foreign-assets/src/lib.rs
  runtime/common/config/xcm/foreignassets.rs
  runtime/common/config/xcm/mod.rs
  tests/src/config.ts
  tests/src/util/index.ts
  tests/src/util/playgrounds/unique.dev.ts
  tests/src/util/playgrounds/unique.ts
  tests/src/xcm/xcmOpal.test.ts
  tests/src/xcm/xcmQuartz.test.ts
  tests/src/xcm/xcmUnique.test.ts
Labels: xcm, CI-xcm

#807 [DO NOT MERGE] fix node only
  .env
Labels: node-only-update, CI-node-only-update

#808 fix: try-runtime polkadot-v0.9.36
  .docker/Dockerfile-try-runtime
  Cargo.lock
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/cli/src/service.rs
  runtime/common/runtime_apis.rs
  runtime/opal/Cargo.toml
  runtime/quartz/Cargo.toml
  runtime/unique/Cargo.toml
Labels: forkless, CI-forkless
